/* banco.js — banco de preguntas para práctica INTERCALADA entre clases.
   Cada clase nueva AGREGA sus preguntas a este array (campo "clase": "cNN").
   La práctica mezcla preguntas de varias clases: ahí se ve si articulás. */
window.BANCO = [
  // ---------------- Clase 1 ----------------
  { clase: "c01", tags: ["epistemología"],
    q: "¿Quién defiende la cientificidad del psicoanálisis y quiénes la niegan?",
    a: "<b>Klimovsky</b> la defiende (misma 'estructura profunda' que toda ciencia). La niegan <b>Popper</b> (no es falsable) y <b>Bunge</b> (pseudociencia)." },
  { clase: "c01", tags: ["epistemología"],
    q: "Distinguí valor epistemológico de valor metodológico en el psicoanálisis (Klimovsky).",
    a: "La <b>metodología</b> es <i>sui generis</i> (asociación libre, sueños, transferencia); la <b>epistemología</b> plantea los mismos problemas que la física (términos teóricos + reglas de correspondencia)." },
  { clase: "c01", tags: ["freud"],
    q: "¿Por qué se dice que Freud pasa de una 'psicología hidráulica' a una 'psicología del conflicto'?",
    a: "De ver el síntoma como afecto estancado que debe drenar (catarsis) a verlo como <b>formación de compromiso</b> entre el deseo y la defensa." },
  { clase: "c01", tags: ["lacan", "ciencia"],
    q: "Explicá: 'el sujeto debe quedar excluido del campo de la ciencia' (Lacan).",
    a: "La ciencia moderna matematiza la naturaleza y excluye la subjetividad (Descartes: garantía en Dios). El sujeto retorna ante las <b>consecuencias</b> de la ciencia; de él se ocupa el psicoanálisis." },
  { clase: "c01", tags: ["lacan", "otro"],
    q: "Diferenciá <i>otro</i> (minúscula) de <b>Otro</b> (mayúscula).",
    a: "<i>otro</i> = el semejante, dimensión imaginaria (espejo). <b>Otro</b> = lugar simbólico, el campo del lenguaje que preexiste al sujeto." },
  { clase: "c01", tags: ["escuelas"],
    q: "¿Cuál es el acento de cada una de las 3 escuelas pos-freudianas?",
    a: "<b>Americana</b>: el yo adaptativo (rechaza la pulsión de muerte). <b>Inglesa</b>: estadios tempranos, Klein/Winnicott. <b>Francesa</b>: retorno a Freud, el Otro, los registros ISR (Lacan)." },

  // ---------------- Clase 2 ----------------
  { clase: "c02", tags: ["sueño"],
    q: "Diferenciá contenido manifiesto de pensamientos latentes y nombrá su relación.",
    a: "CM = el relato recordado (fachada desfigurada); POL = el material genuino de las asociaciones. Relación de <b>traducción</b> (el sueño es un <b>rebus</b>: se lee por la referencia signante)." },
  { clase: "c02", tags: ["sueño", "leyes"],
    q: "¿Cuáles son los 4 procedimientos del trabajo del sueño?",
    a: "Condensación, desplazamiento, miramiento por la figurabilidad y elaboración secundaria." },
  { clase: "c02", tags: ["deseo"],
    q: "¿Por qué el sueño es un cumplimiento de deseo? (empresario / capitalista)",
    a: "El resto diurno (empresario) se alía con el deseo inconsciente infantil (capitalista, que aporta el gasto psíquico). Modelo: la vivencia primaria de satisfacción." },
  { clase: "c02", tags: ["metapsicología"],
    q: "Proceso primario vs. secundario: meta de cada uno.",
    a: "Primario (Icc): libre drenaje → <b>identidad perceptiva</b> (alucina el objeto). Secundario (Prcc/Cc): inhibición → <b>identidad de pensamiento</b> (principio de realidad)." },
  { clase: "c02", tags: ["articulación", "c04"],
    q: "¿Cómo relee Lacan (C4) la condensación y el desplazamiento de Freud (C2/C3)?",
    a: "Condensación → <b>metáfora</b>; desplazamiento → <b>metonimia</b>. Y el deseo ligado a la falta → deseo como <b>metonimia de la falta-en-ser</b>." },

  // ---------------- Clase 3 ----------------
  { clase: "c03", tags: ["represión"],
    q: "¿Cuáles son los dos tiempos de la represión y qué resulta del primero?",
    a: "Represión <b>primordial</b> (deniega el acceso a la conciencia → <b>fijación</b>, supuesto teórico) y represión <b>propiamente dicha</b> (<i>Nachdrängen</i>, sobre los retoños)." },
  { clase: "c03", tags: ["represión"],
    q: "¿Por qué la represión es 'móvil' y no definitiva?",
    a: "Exige un gasto de fuerza constante (<i>Druck</i> vs. <i>Gegendruck</i>): lo reprimido presiona hacia lo Cc; si el gasto cesa, irrumpe (p. ej. el sueño)." },
  { clase: "c03", tags: ["pulsión", "trampa"],
    q: "¿Se reprime la pulsión?",
    a: "No: se reprime su <b>agencia representante</b> (la representación). La pulsión es un concepto fronterizo; el <b>monto de afecto</b> sigue otro destino." },
  { clase: "c03", tags: ["inconsciente"],
    q: "Nombrá las 4 leyes (propiedades) del sistema inconsciente.",
    a: "Ausencia de contradicción · proceso primario (desplazamiento + condensación) · atemporalidad · sustitución de la realidad por el principio de placer." },
  { clase: "c03", tags: ["articulación", "c04"],
    q: "¿Qué concepto de C3 anticipa la 'primacía del significante' de Lacan (C4)?",
    a: "La <b>representación-palabra</b> (<i>Wortvorstellung</i>) y el trato de las palabras como cosas/rebus (Signorelli): la letra importa más que el sentido." },

  // ---------------- Clase 4 ----------------
  { clase: "c04", tags: ["significante"],
    q: "¿En qué consiste el triple movimiento que Lacan le hace al signo (S/s)?",
    a: "Inversión (el significante S va arriba y determina) · apertura del abrochamiento (el significado se desliza → punto de capitón) · barrera resistente a la significación." },
  { clase: "c04", tags: ["significante", "articulación", "c02", "c03"],
    q: "¿Con qué pares de Jakobson relee Lacan la condensación y el desplazamiento?",
    a: "Condensación → <b>metáfora</b> (sustitución, franquea la barra, <i>paso-de-sentido</i>). Desplazamiento → <b>metonimia</b> (contigüidad, la barra se mantiene, <i>poco-de-sentido</i>)." },
  { clase: "c04", tags: ["significante", "trampa"],
    q: "¿Qué diferencia hay entre la condensación freudiana y la metáfora lacaniana?",
    a: "La condensación <b>empobrece</b> (elisión); la metáfora <b>enriquece</b> la lengua con un sentido nuevo (<i>paso-de-sentido</i>)." },
  { clase: "c04", tags: ["otro"],
    q: "Diferenciá alienación y separación. ¿Qué pasa si la separación fracasa?",
    a: "Alienación: el sujeto es tomado por el lenguaje del Otro ('eso habla'). Separación: hiato entre 'yo digo' y 'eso habla' (poder mentir). Si fracasa → <b>psicosis</b>." },
  { clase: "c04", tags: ["deseo"],
    q: "¿Por qué el deseo es 'metonimia de la falta-en-ser'?",
    a: "Porque ninguna significación remite a un objeto último: el deseo se <b>desliza</b> de significante en significante ('deseo de otra cosa'), sin colmar la falta de ser." },
  { clase: "c04", tags: ["deseo"],
    q: "¿Qué quiere decir '¿Che vuoi?' y con qué afecto se liga?",
    a: "'¿Qué me quieres?': la pregunta por qué objeto soy para el deseo del Otro. Se liga a la <b>angustia</b> (el objeto a, real, no representable)." },

  // ---------------- Clase 5 ----------------
  { clase: "c05", tags: ["edipo"],
    q: "¿Por qué el complejo de Edipo es el 'complejo nuclear de las neurosis'?",
    a: "Es el núcleo de deseos incestuosos y parricidas del que parten las neurosis; <i>Edipo Rey</i> es el cumplimiento de deseo de la infancia." },
  { clase: "c05", tags: ["falo", "trampa"],
    q: "En la fase fálica, ¿cuál es la polaridad sexual? ¿Y el falo es el pene?",
    a: "La polaridad es <b>fálico/castrado</b> (no masculino/femenino). El <b>falo</b> no es el pene: es un valor simbólico (lo que se tiene/falta)." },
  { clase: "c05", tags: ["edipo", "disimetría"],
    q: "¿Qué disimetría hay entre el Edipo del varón y el de la niña?",
    a: "La castración <b>termina</b> el Edipo del varón (amenaza → superyó severo) pero lo <b>inaugura</b> en la niña (descubre la falta → gira al padre)." },
  { clase: "c05", tags: ["edipo"],
    q: "¿Cuáles son los saldos del sepultamiento del Edipo?",
    a: "Superyó (investiduras → identificaciones) · desexualización/sublimación · período de latencia. El sepultamiento es <b>más que represión</b>." },
  { clase: "c05", tags: ["identificación", "articulación", "c10"],
    q: "Diferenciá identificación de elección de objeto.",
    a: "Identificación = lo que querría <b>ser</b> (recae en el sujeto del yo). Elección de objeto = lo que querría <b>tener</b> (recae en el objeto)." },
  { clase: "c05", tags: ["articulación", "c07"],
    q: "¿Qué lectura del falo en C5 anticipa la 'metáfora paterna' de Lacan (C7)?",
    a: "El falo como <b>valor simbólico</b> ('lo que alguien tiene y a otro le falta', lo que responde al deseo materno), no como órgano." },

  // ---------------- Clase 6 ----------------
  { clase: "c06", tags: ["pulsión", "trampa"],
    q: "¿En qué se diferencia la pulsión del instinto?",
    a: "El instinto (animal) tiene objeto y meta fijos (reproducción); la pulsión es un concepto fronterizo somático/psíquico <b>sin objeto ni meta naturales</b> (el objeto es lo más contingente)." },
  { clase: "c06", tags: ["pulsión"],
    q: "Nombrá los 4 componentes de la pulsión y cuál es el más contingente.",
    a: "Esfuerzo (Drang), meta (Ziel), objeto (Objekt), fuente (Quelle). El más contingente es el <b>objeto</b>." },
  { clase: "c06", tags: ["pulsión"],
    q: "¿Qué es el apuntalamiento (Anlehnung)?",
    a: "La pulsión sexual nace sostenida en la autoconservación (el chupeteo en el acto de alimentarse) y luego se independiza buscando placer de órgano." },
  { clase: "c06", tags: ["pulsión", "perversión"],
    q: "¿Qué significa que 'la neurosis es el negativo de la perversión'?",
    a: "El perverso <b>actúa</b> las pulsiones parciales; el neurótico las <b>reprime</b> y retornan disfrazadas en el síntoma (compromiso libido/represión)." },
  { clase: "c06", tags: ["pulsión"],
    q: "En los destinos de pulsión, ¿qué cambia en el 'trastorno hacia lo contrario' y en la 'vuelta sobre la persona propia'?",
    a: "En el trastorno hacia lo contrario cambia la <b>meta</b> (activo↔pasivo). En la vuelta sobre la persona propia cambia el <b>objeto</b> (al yo), se mantiene la meta." },
  { clase: "c06", tags: ["articulación", "c08"],
    q: "¿Qué destino de pulsión de C6 anticipa la pulsión de muerte de C8?",
    a: "El <b>masoquismo</b> ('sadismo vuelto hacia el yo') y la vuelta sobre la persona propia; junto con la compulsión de repetición, anticipan el más allá del principio de placer." },

  // ---------------- Clase 7 ----------------
  { clase: "c07", tags: ["edipo", "lacan"],
    q: "¿Qué es la metáfora paterna?",
    a: "Una <b>sustitución significante</b>: el <b>Nombre-del-Padre</b> (la Ley) ocupa el lugar del <b>deseo de la madre</b>, nombrándolo y sustituyendo el capricho por la Ley." },
  { clase: "c07", tags: ["edipo", "lacan"],
    q: "Nombrá los tres tiempos del Edipo en Lacan.",
    a: "1.º: ser el falo (padre velado). 2.º: la Ley/interdicción (padre privador). 3.º: el padre del don (tiene el falo) → de <b>ser</b> a <b>tener</b> (Ideal del yo)." },
  { clase: "c07", tags: ["pulsión", "lacan"],
    q: "¿Qué es el objeto a en la pulsión y qué diferencia hay entre aim y goal?",
    a: "El objeto a es un <b>vacío</b> que la pulsión <b>contornea</b> (no un objeto). <b>Aim</b> = el trayecto (se satisface); <b>goal</b> = el fin reproductivo (no se alcanza)." },
  { clase: "c07", tags: ["klein"],
    q: "Diferenciá la posición esquizoparanoide de la depresiva (Klein).",
    a: "Esquizoparanoide: escisión, objeto parcial, angustia persecutoria. Depresiva: integración, objeto total, culpa y reparación." },
  { clase: "c07", tags: ["articulación", "c04", "c05"],
    q: "¿Por qué la metáfora paterna 'es una metáfora' (C4) y cómo relee el falo de C5?",
    a: "Porque es una <b>sustitución significante</b> (un significante ocupa el lugar de otro). Relee el falo de C5 como el <b>significante</b> del deseo materno (la 'x')." },
  { clase: "c07", tags: ["articulación", "psicosis", "c11"],
    q: "¿Qué pasa cuando la metáfora paterna no opera?",
    a: "Su <b>forclusión</b> (el Nombre-del-Padre no se inscribe) define la <b>psicosis</b> (transversal). El 1.º tiempo (ser el falo) prepara el estadio del espejo (C11)." },

  // ---------------- Clase 8 ----------------
  { clase: "c08", tags: ["mas-alla"],
    q: "¿Cuáles son las objeciones que llevan al 'más allá del principio de placer'?",
    a: "Pseudo-objeción (principio de realidad, que aplaza) · sueños traumáticos · Fort-Da · <b>compulsión de repetición</b> en la transferencia (la más relevante)." },
  { clase: "c08", tags: ["mas-alla", "trampa"],
    q: "Diferenciá angustia, miedo y terror.",
    a: "Angustia: peligro incierto pero con <b>preparación</b>. Miedo: <b>objeto</b> de peligro determinado. Terror: peligro <b>sin preparación</b> (lo que falta en el trauma)." },
  { clase: "c08", tags: ["mas-alla"],
    q: "¿Qué es el trauma según el modelo de la vesícula, y qué tarea impone?",
    a: "Una <b>perforación de la protección antiestímulo (Reizschutz)</b> por excitación masiva → energía no ligada. Impone <b>ligar (Bindung)</b>, tarea previa al principio de placer." },
  { clase: "c08", tags: ["pulsión-muerte"],
    q: "¿Por qué la pulsión de muerte es 'conservadora' y cuál es el nuevo dualismo?",
    a: "Busca restaurar un estado anterior (retorno a lo inorgánico, Nirvana). Nuevo dualismo: <b>Eros</b> (sexuales + autoconservación, liga) vs. <b>pulsión de muerte</b> (desmezcla)." },
  { clase: "c08", tags: ["articulación", "c06"],
    q: "¿Cómo se reformulan sadismo y masoquismo tras 1920?",
    a: "Sadismo = pulsión de muerte <b>desplazada al objeto</b>; masoquismo primario = esa pulsión <b>vuelta al yo</b>. (Reformula los destinos de pulsión de C6.)" },
  { clase: "c08", tags: ["articulación", "c07", "goce"],
    q: "¿Cómo lee Lacan el 'más allá' / el retorno a lo inorgánico?",
    a: "No como muerte biológica (Nirvana, Freud), sino como <b>insistencia del significante</b> y repetición del circuito pulsional alrededor del <b>objeto a</b> → el <b>goce</b>." },

  // ---------------- Clase 9 ----------------
  { clase: "c09", tags: ["narcisismo"],
    q: "¿Qué es el narcisismo y por qué es el momento constitutivo del yo?",
    a: "La investidura <b>libidinal del yo</b>. El yo nace cuando una <b>imagen</b> (que viene del Otro) es investida; antes solo hay cuerpo fragmentado y autoerotismo." },
  { clase: "c09", tags: ["narcisismo"],
    q: "Explicá la metáfora de la ameba.",
    a: "El yo extiende <b>seudópodos</b> (libido de objeto) hacia los objetos sin perderse; queda una <b>reserva</b> (libido yoica). El yo solo existe <b>investido</b>." },
  { clase: "c09", tags: ["narcisismo"],
    q: "¿Qué instancias surgen de la caída del narcisismo infantil?",
    a: "El <b>Ideal del yo</b> (la castración + el camino al ideal) y la <b>conciencia moral</b> (vigila y penaliza al yo). El motor de la caída es el complejo de castración." },
  { clase: "c09", tags: ["identificación"],
    q: "Nombrá las modalidades de identificación.",
    a: "Primordial (ser, lazo al padre), al rasgo (carácter/síntoma), histérica (comunidad afectiva, masa) y narcisista (melancolía). El yo es un precipitado de identificaciones." },
  { clase: "c09", tags: ["narcisismo", "trampa"],
    q: "Diferenciá enamoramiento, paranoia y melancolía (circuito yo↔objeto).",
    a: "Enamoramiento: objeto sobreinvestido, yo humillado. Paranoia: ruptura del circuito → delirio. Melancolía: el yo se identifica con el objeto perdido." },
  { clase: "c09", tags: ["articulación", "c11"],
    q: "¿Qué tesis de C9 anticipa el estadio del espejo de Lacan (C11)?",
    a: "Que el <b>yo es una imagen que viene del Otro</b> (y que antes hay un <b>cuerpo fragmentado</b>): núcleo del estadio del espejo (yo imaginario, alienación)." },

  // ---------------- Clase 10 ----------------
  { clase: "c10", tags: ["topica"],
    q: "¿Qué hecho clínico fuerza el pasaje de la 1.ª a la 2.ª tópica?",
    a: "La <b>resistencia</b> (y la compulsión de repetición): parte del yo, pero el sujeto nada sabe de ella → buena parte del yo es inconsciente." },
  { clase: "c10", tags: ["topica", "trampa"],
    q: "¿Cuál es la frase clave del pasaje a la segunda tópica?",
    a: "\"Todo lo <b>reprimido</b> es inconsciente, pero <b>no todo lo inconsciente es reprimido</b>\" (parte del yo y del superyó también lo son)." },
  { clase: "c10", tags: ["topica"],
    q: "Nombrá y caracterizá las tres instancias de la segunda tópica.",
    a: "Ello (libido, placer, Icc), yo (derivado del ello por el mundo exterior; razón/realidad; jinete y caballo) y superyó (heredero del Edipo; ideal + prohibición)." },
  { clase: "c10", tags: ["topica"],
    q: "¿Qué son los vasallajes del yo y sus tres angustias?",
    a: "El yo sirve a tres amos: mundo exterior (angustia realista), ello (angustia libidinal) y superyó (angustia de la conciencia moral)." },
  { clase: "c10", tags: ["articulación", "c05", "c09"],
    q: "¿De qué es heredero el superyó y qué instancias de C9 integra?",
    a: "Del <b>sepultamiento del complejo de Edipo</b> (C5); integra el <b>Ideal del yo</b> y la <b>conciencia moral</b> (C9)." },
  { clase: "c10", tags: ["articulación", "c01", "trampa"],
    q: "¿Por qué hay que tener cuidado con la palabra 'estructura' en la segunda tópica?",
    a: "La Ego Psychology la llama 'teoría estructural': 'estructura' = organización de instancias del yo, <b>no</b> la estructura estructuralista de Lacan (trampa de C1)." },

  // ---------------- Clase 11 ----------------
  { clase: "c11", tags: ["yo-lacan"],
    q: "¿Qué es el yo para Lacan y cómo se constituye?",
    a: "Una formación <b>imaginaria</b> y de <b>desconocimiento</b>, constituida en el <b>estadio del espejo</b>: el niño se reconoce en una imagen (que viene del Otro)." },
  { clase: "c11", tags: ["yo-lacan"],
    q: "¿Qué es la prematuración y qué implica para el estadio del espejo?",
    a: "La cría humana nace prematura, con un cuerpo <b>fragmentado</b>; por eso lo imaginario (la imagen unificada) se <b>anticipa</b> a la unidad real del cuerpo." },
  { clase: "c11", tags: ["yo-lacan", "trampa"],
    q: "Diferenciá Yo Ideal i(a) de Ideal del yo I(A).",
    a: "<b>i(a)</b> = imaginario (la imagen narcisista del espejo). <b>I(A)</b> = simbólico (función, en el Otro, que sostiene la imagen en el tiempo). Lo simbólico determina lo imaginario." },
  { clase: "c11", tags: ["yo-lacan"],
    q: "¿Qué es el transitivismo?",
    a: "Atribuir al otro algo propio (o vivirlo como propio) porque yo y semejante son un único lugar; efecto de la constitución imaginaria del yo (lógica paranoica)." },
  { clase: "c11", tags: ["articulación", "c01", "c10"],
    q: "¿En qué se opone Lacan a la Ego Psychology respecto del yo?",
    a: "Ego Psychology: yo fuerte/adaptativo (meta: adaptación). Lacan: yo imaginario/desconocimiento; la adaptación es 'conformismo social'. Cierra el contraste de C1." },
  { clase: "c11", tags: ["articulación", "c09", "sintesis"],
    q: "¿De qué clase freudiana es relectura directa el estadio del espejo?",
    a: "De C9 (narcisismo): \"el yo es una imagen que viene del Otro\" + \"antes hay un cuerpo fragmentado\". Es la tercera 'cosecha' lacaniana (junto a C4 y C7)." },

  // ---------------- Transversal · Psicosis (Belucci 4) ----------------
  { clase: "psi", tags: ["psicosis"],
    q: "¿Qué es la 'cuestión preliminar' y por qué es previa al tratamiento?",
    a: "La posición de la psicosis respecto de la <b>estructura</b>. Lo conceptual y lo clínico están en continuidad topológica: <b>sin cuestión preliminar no hay tratamiento posible</b>." },
  { clase: "psi", tags: ["psicosis", "freud"],
    q: "¿Por qué Freud consideraba 'no analizables' las neurosis narcisistas?",
    a: "Porque (supuestamente) <b>no hay transferencia</b>: la libido se retira de los objetos. Usó 'psicosis' desde 1924; Lacan retoma en 1958." },
  { clase: "psi", tags: ["psicosis", "estructura", "trampa"],
    q: "Diferenciá 'estructura' (singular) de 'estructuras clínicas' (plural).",
    a: "Estructura = el matema del <b>Otro barrado (Ⱥ)</b>. Estructuras clínicas = neurosis, perversión y psicosis (no reductibles; sin pasaje): son <b>posiciones</b> respecto de la falta." },
  { clase: "psi", tags: ["psicosis", "c07"],
    q: "¿Qué define a la psicosis respecto del Padre?",
    a: "El <b>operador paterno no está en funciones</b>: la <b>forclusión del Nombre-del-Padre</b> (fracaso de la metáfora paterna, C7)." },
  { clase: "psi", tags: ["psicosis", "c04"],
    q: "¿Cómo se explica la alucinación (voces impuestas)?",
    a: "Por el fracaso de la <b>separación</b> (C4): lo <b>forcluido de lo simbólico retorna en lo real</b> como alucinación (el Otro perseguidor)." },
  { clase: "psi", tags: ["psicosis", "trampa"],
    q: "¿Qué es el 'neurocentrismo' y por qué evitarlo?",
    a: "Leer al psicótico como un neurótico 'tosco o inacabado'. En cambio hay que <b>recortar la imposibilidad</b> para abrir un campo de posibles (el delirio = intento de restitución)." }
  // ---------------- (las próximas clases agregan acá sus preguntas) ----------------
];

/* Consignas de DESARROLLO (las integradoras de cada clase). El simulador incluye una.
   La respuesta desarrollada modelo está en la pestaña Autoevaluación (pregunta 8) de cada clase. */
window.DESARROLLO = [
  { clase: "c01", ref: "clases/clase-01.html", q: "Desarrollá la relación entre ciencia y sujeto en el psicoanálisis, articulando Klimovsky, el giro de Freud y la tesis de Lacan." },
  { clase: "c02", ref: "clases/clase-02.html", q: "Desarrollá cómo el sueño articula inconsciente y deseo (manifiesto/latente, trabajo del sueño, cumplimiento de deseo, vivencia de satisfacción)." },
  { clase: "c03", ref: "clases/clase-03.html", q: "Desarrollá por qué la represión hace posibles las formaciones del inconsciente (dos tiempos, movilidad, representación/afecto, retorno)." },
  { clase: "c04", ref: "clases/clase-04.html", q: "Desarrollá cómo Lacan relee las leyes del inconsciente con el significante (condensación/desplazamiento → metáfora/metonimia; deseo → falta-en-ser)." },
  { clase: "c05", ref: "clases/clase-05.html", q: "Desarrollá cómo el primado del falo explica la disimetría varón/niña y los saldos (superyó, feminidad)." },
  { clase: "c06", ref: "clases/clase-06.html", q: "Desarrollá por qué la sexualidad humana se rige por la pulsión y no por el instinto (4 componentes, apuntalamiento, 'neurosis = negativo de la perversión')." },
  { clase: "c07", ref: "clases/clase-07.html", q: "Desarrollá cómo Lacan relee el Edipo/castración (metáfora paterna, tres tiempos) y la pulsión (objeto a, parcialidad)." },
  { clase: "c08", ref: "clases/clase-08.html", q: "Desarrollá por qué la compulsión de repetición obliga a un 'más allá del principio de placer' (objeciones, trauma/Bindung, pulsión de muerte, placer ≠ satisfacción)." },
  { clase: "c09", ref: "clases/clase-09.html", q: "Desarrollá cómo se constituye el yo en Freud (narcisismo/ameba, caída del narcisismo infantil → Ideal del yo / conciencia moral, identificación)." },
  { clase: "c10", ref: "clases/clase-10.html", q: "Desarrollá el pasaje de la primera a la segunda tópica (hechos clínicos, el yo inconsciente, la nueva articulación ello/yo/superyó)." },
  { clase: "c11", ref: "clases/clase-11.html", q: "Desarrollá la teoría del yo de Lacan (estadio del espejo, i(a)/I(A)) como relectura de C9 y C10, y su oposición a la Ego Psychology." },
  { clase: "psi", ref: "psicosis.html", q: "Desarrollá la psicosis como posición respecto de la estructura, conectando la forclusión del Nombre-del-Padre (C7), el fracaso de la separación (C4) y la cuestión del yo/registros (C11)." }
];
